export const PROPERTIES_DATA: Record<string, any> = {
  '1': {
    name: 'Skyline Luxury Villa',
    location: 'Indiranagar, Bangalore',
    price: '₹ 5.2 Cr',
    description: 'A magnificent 4BHK villa offering unparalleled luxury and privacy. Features a private pool, landscaped garden, and state-of-the-art home automation.',
    type: 'Villa',
    beds: 4,
    baths: 4,
    sqft: '3,500',
    status: 'Ready to Move',
    isFeatured: true,
    builder: 'Skyline Developers',
    builderExperience: '15+ Years',
    totalProjects: '24',
    builderDescription: 'Skyline Developers is a premier real estate firm known for luxury residential projects across Bangalore.',
    reraId: 'PRM/KA/RERA/12345',
    possession: 'Immediate',
    trustScore: 82,
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    features: [
      { icon: 'pool', label: 'Private Pool' },
      { icon: 'shield-checkmark', label: 'Gated Security' },
      { icon: 'car', label: '3 Parking Slots' },
      { icon: 'leaf', label: 'Garden' },
    ],
    amenities: {
      Sports: ['Swimming Pool', 'Gymnasium', 'Tennis Court'],
      Security: ['24/7 Security', 'CCTV Camera', 'Intercom'],
      Leisure: ['Club House', 'Party Hall', 'Indoor Games'],
    },
    faqs: [
      { q: 'Is the project RERA registered?', a: 'Yes, the project is RERA registered with ID PRM/KA/RERA/12345.' },
      { q: 'What is the possession date?', a: 'The project is ready to move with immediate possession.' },
    ],
    priceHistory: [
      { month: 'Jan', value: 4.8 },
      { month: 'Feb', value: 4.9 },
      { month: 'Mar', value: 5.0 },
      { month: 'Apr', value: 5.1 },
      { month: 'May', value: 5.2 },
    ],
    rooms: [
      {
        id: 'living',
        name: 'Living Room',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop',
        hotspots: [
          { x: 0.7, label: 'Go to Garden', targetRoomId: 'garden' }
        ]
      },
      {
        id: 'garden',
        name: 'Private Garden',
        image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?q=80&w=1000&auto=format&fit=crop',
        hotspots: [
          { x: 0.3, label: 'Back to Living Room', targetRoomId: 'living' }
        ]
      }
    ],
    coordinates: {
      latitude: 12.9716,
      longitude: 77.5946,
    },
    timeline: [
      { date: 'Mar 2022', label: 'Foundation Completed', status: 'completed' },
      { date: 'Sep 2022', label: 'Structure Completed', status: 'completed' },
      { date: 'Jan 2023', label: 'Finishing Works', status: 'completed' },
      { date: 'May 2023', label: 'Handover Started', status: 'completed' },
    ],
    localityInsights: [
      { label: '1 Year', value: '+15.2%', trend: 'up' },
      { label: '3 Years', value: '+42.5%', trend: 'up' },
      { label: '5 Years', value: '+65.8%', trend: 'up' },
    ],
    localityDescription: 'Indiranagar remains Bangalore\'s most sought-after residential hub with consistent capital appreciation and high rental yields.',
    avgPrice: '₹ 45,000/sqft',
    priceRange: '₹ 35k - 65k/sqft',
    localityAdvantages: ['Proximity to EGL', 'Metro Connectivity', 'Elite neighborhood'],
    localityScores: [
      { label: 'Safety', score: 9.0, icon: 'shield-checkmark' },
      { label: 'Connectivity', score: 9.5, icon: 'bus' },
      { label: 'Lifestyle', score: 9.8, icon: 'restaurant' },
    ],
    aiInsights: {
      score: 92,
      rentalYield: '4.2%',
      sentiment: 'Bullish',
      summary: 'Based on historical data and upcoming infrastructure, this property is in the top 5% for capital appreciation in Bandra West.',
      highlights: ['High Liquidity', 'Premium Builder Trust', 'Tech Hub Proximity'],
    },
    localitySentiment: {
      pros: ['Excellent Nightlife', 'Safe for Women', 'Premium Schools'],
      cons: ['High Property Rates', 'Traffic Congestion'],
    },
  },
  '2': {
    name: 'Azure Heights',
    location: 'Salt Lake, Kolkata',
    price: '₹ 3.8 Cr',
    description: 'Modern 3BHK apartment with panoramic sea views. Located in the heart of the city with world-class amenities including a rooftop infinity pool.',
    type: 'Apartment',
    beds: 3,
    baths: 3,
    sqft: '2,100',
    status: 'Under Construction',
    builder: 'Azure Group',
    builderExperience: '10+ Years',
    totalProjects: '12',
    builderDescription: 'Azure Group specializes in high-end residential properties with a focus on sustainable architecture.',
    reraId: 'P51900067890',
    possession: 'Dec 2025',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    features: [
      { icon: 'fitness', label: 'Gym' },
      { icon: 'water', label: 'Sea View' },
      { icon: 'business', label: 'Clubhouse' },
      { icon: 'power', label: 'Power Backup' },
    ],
    amenities: {
      Sports: ['Infinity Pool', 'Yoga Deck', 'Jogging Track'],
      Security: ['Smart Access', 'Fire Safety', 'Video Door Phone'],
      Convenience: ['Power Backup', 'High Speed Elevators', 'Rain Water Harvesting'],
    },
    faqs: [
      { q: 'What are the maintenance charges?', a: 'Estimated maintenance is ₹3/sqft per month.' },
      { q: 'Are there any hidden costs?', a: 'No, all costs are transparently listed in the price breakup.' },
    ],
    priceHistory: [
      { month: 'Jan', value: 3.4 },
      { month: 'Feb', value: 3.5 },
      { month: 'Mar', value: 3.6 },
      { month: 'Apr', value: 3.7 },
      { month: 'May', value: 3.8 },
    ],
    rooms: [
      {
        id: 'living',
        name: 'Living Room',
        image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.8, label: 'View Balcony', targetRoomId: 'balcony' }]
      },
      {
        id: 'balcony',
        name: 'Sea View Balcony',
        image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.2, label: 'Back to Living', targetRoomId: 'living' }]
      }
    ],
    coordinates: {
      latitude: 22.5726,
      longitude: 88.3639,
    },
    timeline: [
      { date: 'Jan 2023', label: 'Excavation & Foundation', status: 'completed' },
      { date: 'Aug 2023', label: 'Plinth Level', status: 'completed' },
      { date: 'Jun 2024', label: 'Structure Completion', status: 'upcoming' },
      { date: 'Dec 2025', label: 'Possession', status: 'upcoming' },
    ],
    localityInsights: [
      { label: '1 Year', value: '+10.8%', trend: 'up' },
      { label: '3 Years', value: '+28.4%', trend: 'up' },
      { label: '5 Years', value: '+52.1%', trend: 'up' },
    ],
    localityDescription: 'Salt Lake is a planned satellite town in Kolkata, known for its IT hubs and green spaces.',
    avgPrice: '₹ 55,000/sqft',
    priceRange: '₹ 40k - 80k/sqft',
    localityAdvantages: ['IT Hub Proximity', 'Planned Infrastructure', 'Greenery'],
    localityScores: [
      { label: 'Safety', score: 8.8, icon: 'shield-checkmark' },
      { label: 'Connectivity', score: 9.2, icon: 'bus' },
      { label: 'Lifestyle', score: 9.0, icon: 'restaurant' },
    ],
    aiInsights: {
      score: 85,
      rentalYield: '3.8%',
      sentiment: 'Stable',
      summary: 'Azure Heights offers a stable investment with high rental demand due to its central Salt Lake location.',
      highlights: ['Strong Rental Demand', 'Planned Sector', 'Modern Amenities'],
    },
    localitySentiment: {
      pros: ['Green Spaces', 'IT Hub', 'Luxury Lifestyle'],
      cons: ['Limited Public Parking', 'High Maintenance'],
    },
  },
  '3': {
    name: 'Emerald Gardens',
    location: 'Candolim, Goa',
    price: '₹ 2.8 Cr',
    description: 'Elegant 2BHK apartment in a lush green township. Features lake views and proximity to Hiranandani Gardens.',
    type: 'Apartment',
    beds: 2,
    baths: 2,
    sqft: '1,250',
    status: 'Ready to Move',
    builder: 'Emerald Developers',
    builderExperience: '20+ Years',
    totalProjects: '45',
    builderDescription: 'Emerald Developers is a household name in luxury development, focusing on green living and community spaces.',
    reraId: 'P51800099999',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    features: [
      { icon: 'leaf', label: 'Park' },
      { icon: 'water', label: 'Lake View' },
      { icon: 'car', label: 'Parking' },
    ],
    amenities: {
      Sports: ['Badminton Court', 'Kids Play Area', 'Cycling Track'],
      Leisure: ['Amphitheatre', 'Senior Citizen Area', 'Library'],
      Security: ['Perimeter Security', 'Security Cabin', 'Visitor Management'],
    },
    faqs: [
      { q: 'Is it close to the beach?', a: 'Yes, Candolim beach is just 1.2 km away.' },
      { q: 'Is it a gated community?', a: 'Yes, it is a fully gated community with 24/7 security.' },
    ],
    priceHistory: [
      { month: 'Jan', value: 2.2 },
      { month: 'Feb', value: 2.3 },
      { month: 'Mar', value: 2.3 },
      { month: 'Apr', value: 2.4 },
      { month: 'May', value: 2.5 },
    ],
    rooms: [
      {
        id: 'living',
        name: 'Living Room',
        image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.7, label: 'Go to Kitchen', targetRoomId: 'kitchen' }]
      },
      {
        id: 'kitchen',
        name: 'Kitchen',
        image: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.3, label: 'Back to Living', targetRoomId: 'living' }]
      }
    ],
    avgPrice: '₹ 20,000/sqft',
    priceRange: '₹ 18k - 25k/sqft',
    localityInsights: [
      { label: '1 Year', value: '+8.2%', trend: 'up' },
      { label: '3 Years', value: '+22.5%', trend: 'up' },
      { label: '5 Years', value: '+45.8%', trend: 'up' },
    ],
    localityDescription: 'Candolim is a premier coastal destination in North Goa, offering a blend of serene beaches and luxury living.',
    localityAdvantages: ['Beach Proximity', 'High Rental Yield', 'Tourist Hub'],
    localityScores: [
      { label: 'Safety', score: 9.2, icon: 'shield-checkmark' },
      { label: 'Connectivity', score: 8.5, icon: 'bus' },
      { label: 'Lifestyle', score: 8.8, icon: 'restaurant' },
    ],
    aiInsights: {
      score: 82,
      rentalYield: '5.1%',
      sentiment: 'Growth',
      summary: 'Emerald Gardens is a high-yield investment in Goa. The rental yield is higher than the city average, making it ideal for passive income.',
      highlights: ['Best Value for Money', 'Green Township', 'High Rental Yield'],
    },
    localitySentiment: {
      pros: ['Lush Greenery', 'Lake Proximity', 'Planned Infrastructure'],
      cons: ['Distance from South Mumbai', 'Peak Hour Traffic'],
    },
    timeline: [
      { date: 'Jun 2021', label: 'Project Launch', status: 'completed' },
      { date: 'Dec 2021', label: 'Foundation Done', status: 'completed' },
      { date: 'Oct 2022', label: 'Structure Ready', status: 'completed' },
      { date: 'Apr 2023', label: 'Ready for Fit-outs', status: 'completed' },
    ],
  },
  '4': {
    name: 'Gomti View Residency',
    location: 'Gomti Nagar, Lucknow',
    price: '₹ 1.5 Cr',
    description: 'Luxury 3BHK with a direct view of the Gomti River. Experience the best of modern living in Lucknow.',
    type: 'Apartment',
    beds: 3,
    baths: 3,
    sqft: '2,400',
    status: 'Ready to Move',
    builder: 'Lucknow Realty',
    reraId: 'UPRERAPRJ11223',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      {
        id: 'living',
        name: 'Living Room',
        image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.8, label: 'View Balcony', targetRoomId: 'balcony' }]
      },
      {
        id: 'balcony',
        name: 'River View Balcony',
        image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.2, label: 'Back to Living', targetRoomId: 'living' }]
      }
    ],
    features: [{ icon: 'water', label: 'River View' }, { icon: 'fitness', label: 'Gym' }],
    priceHistory: [{ month: 'Jan', value: 1.2 }, { month: 'May', value: 1.5 }],
  },
  '5': {
    name: 'Royal Palms',
    location: 'Jubilee Hills, Hyderabad',
    price: '₹ 4.8 Cr',
    description: 'Spacious 2BHK surrounded by greenery. A peaceful retreat within the city.',
    type: 'Apartment',
    beds: 2,
    baths: 2,
    sqft: '1,150',
    status: 'Ready to Move',
    builder: 'Deccan Developers',
    reraId: 'TSRERAPRJ44556',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      {
        id: 'kitchen',
        name: 'Modular Kitchen',
        image: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.7, label: 'Go to Dining', targetRoomId: 'dining' }]
      },
      {
        id: 'dining',
        name: 'Dining Area',
        image: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.3, label: 'Back to Kitchen', targetRoomId: 'kitchen' }]
      }
    ],
    features: [{ icon: 'leaf', label: 'Park' }, { icon: 'shield-checkmark', label: 'Security' }],
    priceHistory: [{ month: 'Jan', value: 4.2 }, { month: 'May', value: 4.8 }],
  },
  '6': {
    name: 'DLF Zen',
    location: 'Vasant Vihar, Delhi',
    price: '₹ 8.2 Cr',
    description: 'Premium 3BHK in the heart of South Delhi. Modern architecture meets classic elegance.',
    type: 'Apartment',
    beds: 3,
    baths: 3,
    sqft: '1,650',
    status: 'Under Construction',
    isFeatured: true,
    builder: 'DLF Group',
    reraId: 'DLRERAPRJ77889',
    possession: 'Dec 2024',
    image: 'https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      {
        id: 'bedroom',
        name: 'Master Bedroom',
        image: 'https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.6, label: 'Walk-in Closet', targetRoomId: 'closet' }]
      },
      {
        id: 'closet',
        name: 'Walk-in Closet',
        image: 'https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.4, label: 'Back to Bedroom', targetRoomId: 'bedroom' }]
      }
    ],
    features: [{ icon: 'business', label: 'Clubhouse' }, { icon: 'car', label: 'Parking' }],
    priceHistory: [{ month: 'Jan', value: 7.5 }, { month: 'May', value: 8.2 }],
  },
  '7': {
    name: 'Amanora Park',
    location: 'Hadapsar, Pune',
    price: '₹ 2.5 Cr',
    description: 'Ultra-luxury 4BHK in one of the most premium townships in Pune.',
    type: 'Apartment',
    beds: 4,
    baths: 5,
    sqft: '4,200',
    status: 'Ready to Move',
    isFeatured: true,
    builder: 'Amanora Group',
    reraId: 'P52100099001',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      {
        id: 'office',
        name: 'Home Office',
        image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.5, label: 'Go to Lounge', targetRoomId: 'lounge' }]
      },
      {
        id: 'lounge',
        name: 'Private Lounge',
        image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.5, label: 'Back to Office', targetRoomId: 'office' }]
      }
    ],
    features: [{ icon: 'trophy', label: 'Elite Living' }, { icon: 'pool', label: 'Infinity Pool' }],
    priceHistory: [{ month: 'Jan', value: 2.2 }, { month: 'May', value: 2.5 }],
  },
  '8': {
    name: 'Brigade Garden',
    location: 'OMR, Chennai',
    price: '₹ 1.2 Cr',
    description: 'Contemporary 3BHK with world-class amenities and excellent connectivity.',
    type: 'Apartment',
    beds: 3,
    baths: 3,
    sqft: '1,550',
    status: 'Ready to Move',
    builder: 'Oberoi Realty',
    reraId: 'TNRERAPRJ22334',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      {
        id: 'kitchen',
        name: 'Kitchen',
        image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.8, label: 'Utility Area', targetRoomId: 'utility' }]
      },
      {
        id: 'utility',
        name: 'Utility Area',
        image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.2, label: 'Back to Kitchen', targetRoomId: 'kitchen' }]
      }
    ],
    features: [{ icon: 'school', label: 'Near Schools' }, { icon: 'train', label: 'Near Metro' }],
    priceHistory: [{ month: 'Jan', value: 1.0 }, { month: 'May', value: 1.2 }],
  },
  '9': {
    name: 'Adani Shantigram',
    location: 'SG Highway, Ahmedabad',
    price: '₹ 1.8 Cr',
    description: 'A massive integrated township offering a golf course and premium lifestyle.',
    type: 'Apartment',
    beds: 3,
    baths: 3,
    sqft: '1,850',
    status: 'Ready to Move',
    builder: 'Adani Realty',
    reraId: 'GJRERAPRJ55667',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      {
        id: 'living',
        name: 'Living Area',
        image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.7, label: 'Go to Balcony', targetRoomId: 'balcony' }]
      },
      {
        id: 'balcony',
        name: 'Golf View Balcony',
        image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.3, label: 'Back to Living', targetRoomId: 'living' }]
      }
    ],
    features: [{ icon: 'golf', label: 'Golf Course' }, { icon: 'leaf', label: 'Greenery' }],
    priceHistory: [{ month: 'Jan', value: 1.6 }, { month: 'May', value: 1.8 }],
  },
  '10': {
    name: 'Pink City Palace',
    location: 'Malviya Nagar, Jaipur',
    price: '₹ 2.2 Cr',
    description: 'Experience royal living with modern amenities in the heart of Jaipur.',
    type: 'Villa',
    beds: 4,
    baths: 4,
    sqft: '2,800',
    status: 'Ready to Move',
    builder: 'Jaipur Homes',
    reraId: 'RJRERAPRJ88990',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      {
        id: 'bathroom',
        name: 'Royal Bathroom',
        image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.5, label: 'Go to Bedroom', targetRoomId: 'bedroom' }]
      },
      {
        id: 'bedroom',
        name: 'Royal Bedroom',
        image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=1000&auto=format&fit=crop',
        hotspots: [{ x: 0.5, label: 'Back to Bathroom', targetRoomId: 'bathroom' }]
      }
    ],
    features: [{ icon: 'ribbon', label: 'Royal Design' }, { icon: 'shield-checkmark', label: 'Security' }],
    priceHistory: [{ month: 'Jan', value: 2.0 }, { month: 'May', value: 2.2 }],
  },
  '11': {
    name: 'Blue Ridge IT Park',
    location: 'Hinjewadi, Pune',
    price: '₹ 1.1 Cr',
    description: 'Modern 2BHK apartment located in the heart of Pune\'s IT hub. Perfect for professionals seeking a walk-to-work lifestyle.',
    type: 'Apartment',
    beds: 2,
    baths: 2,
    sqft: '1,200',
    status: 'Ready to Move',
    builder: 'Paranjape Schemes',
    reraId: 'P52100000011',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      { id: 'living', name: 'Living Room', image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.7, label: 'Kitchen', targetRoomId: 'kitchen' }] },
      { id: 'kitchen', name: 'Kitchen', image: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.3, label: 'Living', targetRoomId: 'living' }] }
    ],
    features: [{ icon: 'business', label: 'Near IT Park' }, { icon: 'fitness', label: 'Gym' }],
    priceHistory: [{ month: 'Jan', value: 0.95 }, { month: 'May', value: 1.1 }],
  },
  '12': {
    name: 'My Home Avatar',
    location: 'Narsingi, Hyderabad',
    price: '₹ 1.4 Cr',
    description: 'Spacious 3BHK high-rise apartment with world-class amenities and excellent connectivity to the Financial District.',
    type: 'Apartment',
    beds: 3,
    baths: 3,
    sqft: '1,800',
    status: 'Under Construction',
    builder: 'My Home Group',
    reraId: 'TSRERA1200012',
    possession: 'Dec 2025',
    image: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      { id: 'balcony', name: 'Balcony', image: 'https://images.unsplash.com/photo-1513584684374-8bdb74838a0f?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.5, label: 'Living Room', targetRoomId: 'living' }] },
      { id: 'living', name: 'Living Room', image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.5, label: 'Balcony', targetRoomId: 'balcony' }] }
    ],
    features: [{ icon: 'car', label: '2 Parking' }, { icon: 'pool', label: 'Clubhouse' }],
    priceHistory: [{ month: 'Jan', value: 1.25 }, { month: 'May', value: 1.4 }],
  },
  '13': {
    name: 'Casagrand Zenith',
    location: 'Medavakkam, Chennai',
    price: '₹ 85 Lakh',
    description: 'Premium 2BHK apartment in a wellness-themed community. Features over 75+ amenities for a healthy lifestyle.',
    type: 'Apartment',
    beds: 2,
    baths: 2,
    sqft: '1,100',
    status: 'Ready to Move',
    builder: 'Casagrand',
    reraId: 'TNRERA00013',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      { id: 'bedroom', name: 'Master Bedroom', image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.8, label: 'Living', targetRoomId: 'living' }] },
      { id: 'living', name: 'Living Room', image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.2, label: 'Bedroom', targetRoomId: 'bedroom' }] }
    ],
    features: [{ icon: 'leaf', label: 'Wellness Garden' }, { icon: 'bicycle', label: 'Cycling Track' }],
    priceHistory: [{ month: 'Jan', value: 0.78 }, { month: 'May', value: 0.85 }],
  },
  '14': {
    name: 'Green Residency',
    location: 'New Town, Kolkata',
    price: '₹ 7.5 Cr',
    description: 'Luxury 4BHK apartment in the heart of New Town. Experience the pinnacle of high-end living in Kolkata with lush green surroundings.',
    type: 'Apartment',
    beds: 4,
    baths: 4,
    sqft: '3,800',
    status: 'Ready to Move',
    isFeatured: true,
    builder: 'Green Group',
    reraId: 'WBRERA00014',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      { id: 'lounge', name: 'Private Lounge', image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.6, label: 'Dining', targetRoomId: 'dining' }] },
      { id: 'dining', name: 'Dining Area', image: 'https://images.unsplash.com/photo-1534349762230-e0cadf78f505?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.4, label: 'Lounge', targetRoomId: 'lounge' }] }
    ],
    features: [{ icon: 'leaf', label: 'Eco-friendly' }, { icon: 'trophy', label: 'Elite Club' }],
    priceHistory: [{ month: 'Jan', value: 6.8 }, { month: 'May', value: 7.5 }],
  },
  '15': {
    name: 'Godrej Palm Retreat',
    location: 'Sector 150, Noida',
    price: '₹ 2.1 Cr',
    description: 'Resort-style 3BHK living in Noida\'s greenest sector. Low-density development with expansive open spaces.',
    type: 'Apartment',
    beds: 3,
    baths: 3,
    sqft: '1,900',
    status: 'Under Construction',
    builder: 'Godrej Properties',
    reraId: 'UPRERA00015',
    possession: 'June 2025',
    image: 'https://images.unsplash.com/photo-1448630360428-65456885c650?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      { id: 'living', name: 'Living Room', image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.7, label: 'Kitchen', targetRoomId: 'kitchen' }] },
      { id: 'kitchen', name: 'Kitchen', image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.3, label: 'Living', targetRoomId: 'living' }] }
    ],
    features: [{ icon: 'leaf', label: '80% Greenery' }, { icon: 'water', label: 'Pool View' }],
    priceHistory: [{ month: 'Jan', value: 1.85 }, { month: 'May', value: 2.1 }],
  },
  '16': {
    name: 'Purva Oceana',
    location: 'Marine Drive, Kochi',
    price: '₹ 1.9 Cr',
    description: 'Luxury 3BHK waterfront apartment with breathtaking views of the Arabian Sea. Premium finishes and prime location.',
    type: 'Apartment',
    beds: 3,
    baths: 3,
    sqft: '2,200',
    status: 'Ready to Move',
    builder: 'Puravankara',
    reraId: 'K-RERA00016',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      { id: 'balcony', name: 'Sea View Balcony', image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.5, label: 'Living Room', targetRoomId: 'living' }] },
      { id: 'living', name: 'Living Room', image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.5, label: 'Balcony', targetRoomId: 'balcony' }] }
    ],
    features: [{ icon: 'water', label: 'Sea Facing' }, { icon: 'shield-checkmark', label: 'High Security' }],
    priceHistory: [{ month: 'Jan', value: 1.7 }, { month: 'May', value: 1.9 }],
  },
  '17': {
    name: 'Sushma Buildtech',
    location: 'Zirakpur, Chandigarh',
    price: '₹ 1.2 Cr',
    description: 'Elegant 3BHK apartment in a planned township. Features wide roads, landscaped parks, and modern infrastructure.',
    type: 'Apartment',
    beds: 3,
    baths: 3,
    sqft: '1,650',
    status: 'Ready to Move',
    builder: 'Sushma Group',
    reraId: 'PBRERA00017',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      { id: 'kitchen', name: 'Kitchen', image: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.8, label: 'Dining', targetRoomId: 'dining' }] },
      { id: 'dining', name: 'Dining Area', image: 'https://images.unsplash.com/photo-1617806118233-18e1674745ef?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.2, label: 'Kitchen', targetRoomId: 'kitchen' }] }
    ],
    features: [{ icon: 'car', label: 'Covered Parking' }, { icon: 'leaf', label: 'Central Park' }],
    priceHistory: [{ month: 'Jan', value: 1.05 }, { month: 'May', value: 1.2 }],
  },
  '18': {
    name: 'Apollo DB City',
    location: 'Nipania, Indore',
    price: '₹ 95 Lakh',
    description: 'Spacious 3BHK apartment in Indore\'s most premium residential locality. Excellent connectivity to the bypass and city center.',
    type: 'Apartment',
    beds: 3,
    baths: 3,
    sqft: '1,750',
    status: 'Ready to Move',
    builder: 'Apollo Group',
    reraId: 'MPRERA00018',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1591825729269-caeb344f6df2?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      { id: 'living', name: 'Living Area', image: 'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.7, label: 'Bedroom', targetRoomId: 'bedroom' }] },
      { id: 'bedroom', name: 'Bedroom', image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.3, label: 'Living', targetRoomId: 'living' }] }
    ],
    features: [{ icon: 'business', label: 'Prime Location' }, { icon: 'fitness', label: 'Gym' }],
    priceHistory: [{ month: 'Jan', value: 0.85 }, { month: 'May', value: 0.95 }],
  },
  '19': {
    name: 'Acron Waterfront',
    location: 'Baga, Goa',
    price: '₹ 4.2 Cr',
    description: 'Exclusive 3BHK vacation villa with a private pool. Located just minutes away from the vibrant Baga beach.',
    type: 'Villa',
    beds: 3,
    baths: 4,
    sqft: '2,500',
    status: 'Ready to Move',
    builder: 'Acron Developers',
    reraId: 'GOARERA00019',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      { id: 'pool', name: 'Private Pool', image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.5, label: 'Living Room', targetRoomId: 'living' }] },
      { id: 'living', name: 'Living Room', image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.5, label: 'Pool', targetRoomId: 'pool' }] }
    ],
    features: [{ icon: 'pool', label: 'Private Pool' }, { icon: 'umbrella', label: 'Near Beach' }],
    priceHistory: [{ month: 'Jan', value: 3.8 }, { month: 'May', value: 4.2 }],
  },
  '20': {
    name: 'Prestige Lakeside Habitat',
    location: 'Whitefield, Bangalore',
    price: '₹ 3.5 Cr',
    description: 'Massive 3BHK apartment in a Disney-themed township. Overlooks the scenic Varthur Lake with sprawling open spaces.',
    type: 'Apartment',
    beds: 3,
    baths: 3,
    sqft: '2,100',
    status: 'Ready to Move',
    isFeatured: true,
    builder: 'Prestige Group',
    reraId: 'PRM/KA/RERA/00020',
    possession: 'Immediate',
    image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=1000&auto=format&fit=crop',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rooms: [
      { id: 'living', name: 'Living Room', image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.7, label: 'Balcony', targetRoomId: 'balcony' }] },
      { id: 'balcony', name: 'Lake View Balcony', image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1000&auto=format&fit=crop', hotspots: [{ x: 0.3, label: 'Living', targetRoomId: 'living' }] }
    ],
    features: [{ icon: 'water', label: 'Lake View' }, { icon: 'leaf', label: 'Disney Theme' }],
    priceHistory: [{ month: 'Jan', value: 3.1 }, { month: 'May', value: 3.5 }],
  },
};