import { StyleSheet, Platform } from 'react-native';

export const CITY_AVERAGE_DATA: any = {
  location: 'Mumbai Average',
  avgPrice: '₹ 28,000/sqft',
  localityScores: [
    { label: 'Safety', score: 7.2, icon: 'shield-checkmark' },
    { label: 'Connectivity', score: 7.8, icon: 'bus' },
    { label: 'Lifestyle', score: 7.0, icon: 'restaurant' },
  ],
  localityInsights: [
    { label: '1 Year', value: '+8.5%', trend: 'up' },
    { label: '3 Years', value: '+22.0%', trend: 'up' },
    { label: '5 Years', value: '+48.0%', trend: 'up' },
  ],
  localityAdvantages: ['Established Infrastructure', 'Diverse Housing Options', 'Major Employment Hubs'],
};

export const REVIEW_TAGS = ['Safe', 'Family Friendly', 'Clean', 'Well-connected', 'Great Amenities', 'Quiet', 'Value for Money'];

export const MOCK_LEADS = [
  { id: '1', name: 'Amit Shah', status: 'New', source: 'WhatsApp', date: '2 hours ago', notes: 'Interested in 3BHK' },
  { id: '2', name: 'Suresh Raina', status: 'Contacted', source: 'Web', date: '5 hours ago', notes: 'Budget is flexible' },
  { id: '3', name: 'Deepika P.', status: 'Site Visit', source: 'Call', date: 'Yesterday', notes: 'Coming this Sunday' },
];

export const BANK_RATES = [
  { name: 'SBI', rate: 8.4 },
  { name: 'HDFC', rate: 8.5 },
  { name: 'ICICI', rate: 8.7 },
];

export const BANK_OFFERS = [
  { bank: 'SBI', offer: 'Zero processing fee for women borrowers.' },
  { bank: 'HDFC', offer: 'Flat ₹10,000 off on processing fee with HDFC Credit Cards.' },
  { bank: 'ICICI', offer: '0.10% interest rate discount for existing salary account holders.' },
];

export const parsePrice = (priceStr: string) => {
  const cleanStr = priceStr.replace(/,/g, '').toLowerCase();
  const num = parseFloat(cleanStr.replace(/[^\d.]/g, '')) || 0;
  if (priceStr.toLowerCase().includes('cr')) return num * 10_000_000;
  if (priceStr.toLowerCase().includes('lakh')) return num * 100_000;
  return isNaN(num) ? 0 : num;
};

export const styles = StyleSheet.create({
  mediaContainer: { height: '100%', width: '100%' },
  mainImage: { width: '100%', height: '100%' },

  placeholder3D: {
    flex: 1,
    backgroundColor: '#020617',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  threeDImage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    opacity: 0.6,
  },
  overlay3D: {
    position: 'absolute',
    bottom: 80,
    alignItems: 'center',
    gap: 10,
  },
  placeholderText: {
    color: '#22d3ee',
    fontSize: 16,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },

  backButton: {
    position: 'absolute',
    top: 50,
    left: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 10,
    borderRadius: 20,
  },
  headerActions: {
    position: 'absolute',
    top: 50,
    right: 20,
    flexDirection: 'row',
    gap: 12,
  },
  actionButton: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 10,
    borderRadius: 20,
  },
  videoControlsOverlay: {
    position: 'absolute',
    bottom: 110,
    right: 20,
    gap: 10,
  },
  controlButton: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 12,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  speedText: {
    color: '#22d3ee',
    fontSize: 11,
    fontWeight: '800',
  },
  progressBarContainer: {
    position: 'absolute',
    bottom: 90,
    left: 20,
    right: 20,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#22d3ee',
  },
  videoLoader: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  centralControlContainer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centralControlButton: {
    backgroundColor: 'rgba(34, 211, 238, 0.2)',
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#22d3ee',
    shadowColor: '#22d3ee',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 15,
  },
  virtualTourBadge: {
    position: 'absolute',
    top: 20,
    left: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(34, 211, 238, 0.5)',
  },
  virtualTourText: {
    color: '#22d3ee',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  doubleTapOverlay: {
    position: 'absolute',
    top: '35%',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  doubleTapCircle: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  doubleTapText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  bottomControlsWrapper: {
    position: 'absolute',
    bottom: 85,
    left: 20,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  videoErrorOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    gap: 12,
  },
  videoErrorText: {
    color: '#e5e7eb',
    fontSize: 14,
    fontWeight: '600',
  },
  retryButton: {
    backgroundColor: '#22d3ee',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 12,
  },
  retryButtonText: {
    color: '#020617',
    fontWeight: '700',
  },

  toggleContainer: {
    position: 'absolute',
    bottom: 40,
    alignSelf: 'center',
    flexDirection: 'row',
    backgroundColor: '#0f172a',
    borderRadius: 25,
    padding: 4,
  },
  toggleBtn: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
  },
  activeToggle: { backgroundColor: '#22d3ee' },
  toggleText: { color: '#94a3b8', fontWeight: '600' },
  activeToggleText: { color: '#020617' },

  headerInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  headerInfoMobile: {
    flexDirection: 'column',
    gap: 12,
  },
  statusBadge: {
    backgroundColor: 'rgba(34, 211, 238, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: 'rgba(34, 211, 238, 0.4)',
  },
  statusText: {
    color: '#22d3ee',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  title: { fontSize: 32, fontWeight: '900', color: '#fff', letterSpacing: -1, lineHeight: 38 },
  titleMobile: { fontSize: 26, lineHeight: 32 },
  titleSmall: { fontSize: 22, lineHeight: 28 },
  location: { color: '#cbd5e1' },
  price: { fontSize: 30, fontWeight: '900', color: '#22d3ee', letterSpacing: -0.5 },
  priceMobile: { fontSize: 24 },
  priceColumn: { alignItems: 'flex-end' },
  priceColumnMobile: { alignItems: 'flex-start' },

  tabBar: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#1e293b',
  },
  tabBarContent: { paddingBottom: 8, gap: 24 },
  tabItem: { paddingBottom: 8 },
  activeTabItem: { borderBottomWidth: 2, borderBottomColor: '#22d3ee' },
  tabText: { color: '#64748b', fontSize: 14, fontWeight: '600' },
  activeTabText: { color: '#22d3ee' },

  emiText: { color: '#94a3b8', fontSize: 12, fontWeight: '600', marginTop: 2 },
  priceBreakupLink: { color: '#22d3ee', fontSize: 11, fontWeight: '700', textDecorationLine: 'underline', marginTop: 4 },

  overviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    borderRadius: 20,
    padding: 20,
    marginVertical: 20,
    borderWidth: 1,
    borderColor: '#1e293b',
  },
  overviewItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
  },
  overviewLabel: { color: '#64748b', fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  overviewValue: { color: '#e2e8f0', fontSize: 13, fontWeight: '600' },

  specsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  specsRowMobile: {
    flexWrap: 'wrap',
    gap: 10,
  },
  specItem: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  specItemMobile: {
    width: '48%',
  },
  specText: {
    color: '#e5e7eb',
    fontSize: 15,
    fontWeight: '600',
  },

  divider: {
    height: 1,
    backgroundColor: '#1e293b',
    marginVertical: 20,
  },

  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#e5e7eb',
    marginBottom: 16,
    paddingLeft: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#22d3ee',
  },

  featuresGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  featureItem: {
    flexDirection: 'row',
    gap: 8,
    width: '48%',
    marginBottom: 12,
    alignItems: 'center',
  },
  featureLabel: { color: '#cbd5e1' },

  description: {
    color: '#94a3b8',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 24,
  },

  highlightsContainer: {
    backgroundColor: '#0f172a',
    padding: 16,
    borderRadius: 16,
    marginBottom: 24,
    gap: 10,
  },
  highlightItem: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  highlightText: { color: '#e2e8f0', fontSize: 14, fontWeight: '500' },

  amenitiesContainer: {
    backgroundColor: 'transparent',
    padding: 0,
    borderRadius: 0,
    borderWidth: 1.5,
    borderColor: 'transparent',
    marginBottom: 24,
  },
  amenityCategory: { marginTop: 20 },
  amenityCategoryTitle: { color: '#22d3ee', fontSize: 12, fontWeight: '800', textTransform: 'uppercase', marginBottom: 12, letterSpacing: 1 },
  amenityGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  amenityItem: { flexDirection: 'row', alignItems: 'center', gap: 8, width: '47%' },
  amenityDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: '#22d3ee' },
  amenityText: { color: '#cbd5e1', fontSize: 13 },

  faqContainer: { gap: 12, marginBottom: 32 },
  faqItem: {
    backgroundColor: '#0f172a',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1e293b',
  },
  faqQuestion: { color: '#fff', fontSize: 14, fontWeight: '700', marginBottom: 8 },
  faqAnswer: { color: '#94a3b8', fontSize: 13, lineHeight: 18 },

  configTable: {
    backgroundColor: '#0f172a',
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#1e293b',
    marginBottom: 24,
  },
  configHeader: {
    flexDirection: 'row',
    backgroundColor: '#1e293b',
    padding: 12,
  },
  configHeaderCell: { flex: 1, color: '#94a3b8', fontSize: 11, fontWeight: '800', textTransform: 'uppercase' },
  configRow: {
    flexDirection: 'row',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#1e293b',
  },
  configCellType: { flex: 1, color: '#fff', fontWeight: '700', fontSize: 13 },
  configCell: { flex: 1, color: '#cbd5e1', fontSize: 13 },
  configCellPrice: { flex: 1, color: '#22d3ee', fontWeight: '800', fontSize: 13 },

  builderProfileCard: {
    backgroundColor: 'transparent',
    padding: 0,
    borderRadius: 0,
    borderWidth: 1,
    borderColor: 'transparent',
    marginBottom: 24,
  },
  builderHeader: { flexDirection: 'row', alignItems: 'center', gap: 16, marginBottom: 20 },
  builderLogoPlaceholder: { width: 50, height: 50, borderRadius: 12, backgroundColor: '#020617', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#1e293b' },
  builderTitleInfo: { flex: 1 },
  builderNameText: { color: '#fff', fontSize: 18, fontWeight: '700' },
  builderExperienceText: { color: '#94a3b8', fontSize: 13, fontWeight: '500' },
  builderStatsRow: { flexDirection: 'row', backgroundColor: '#020617', padding: 16, borderRadius: 12, marginBottom: 16 },
  builderStatItem: { flex: 1, alignItems: 'center' },
  builderStatValue: { color: '#22d3ee', fontSize: 18, fontWeight: '800' },
  builderStatLabel: { color: '#64748b', fontSize: 11, fontWeight: '600', textTransform: 'uppercase', marginTop: 2 },
  builderStatDivider: { width: 1, height: 30, backgroundColor: '#1e293b' },
  builderDescriptionText: { color: '#94a3b8', fontSize: 13, lineHeight: 20 },

  timelineContainer: {
    backgroundColor: 'transparent',
    padding: 0,
    borderRadius: 0,
    borderWidth: 1,
    borderColor: 'transparent',
    marginBottom: 24,
  },
  timelineItem: { flexDirection: 'row', minHeight: 60 },
  timelineLeft: { alignItems: 'center', width: 20, marginRight: 16 },
  timelineDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#334155', zIndex: 1 },
  timelineDotActive: { backgroundColor: '#22d3ee', shadowColor: '#22d3ee', shadowRadius: 4, shadowOpacity: 0.5 },
  timelineLine: { position: 'absolute', top: 12, bottom: 0, width: 2, backgroundColor: '#1e293b' },
  timelineRight: { flex: 1, paddingBottom: 20 },
  timelineDate: { color: '#22d3ee', fontSize: 12, fontWeight: '700', marginBottom: 2 },
  timelineLabel: { color: '#e2e8f0', fontSize: 14, fontWeight: '500' },

  connectivityContainer: { marginBottom: 24, gap: 8 },
  connectivityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0f172a',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1e293b',
  },
  connectivityIcon: { width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(34, 211, 238, 0.1)', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  connectivityName: { flex: 1, color: '#e2e8f0', fontSize: 14, fontWeight: '500' },
  connectivityDistance: { color: '#94a3b8', fontSize: 12, fontWeight: '700' },

  localityScoreContainer: {
    backgroundColor: 'transparent',
    padding: 0,
    borderRadius: 0,
    borderWidth: 1,
    borderColor: 'transparent',
    marginBottom: 24,
    gap: 16,
  },
  scoreRow: { gap: 8 },
  scoreHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  scoreLabelContainer: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  scoreLabel: { color: '#e2e8f0', fontSize: 14, fontWeight: '600' },
  scoreValue: { color: '#22d3ee', fontSize: 14, fontWeight: '800' },
  scoreBarBg: { height: 6, backgroundColor: '#020617', borderRadius: 3, overflow: 'hidden' },
  scoreBarFill: { height: '100%', backgroundColor: '#22d3ee', borderRadius: 3 },

  reviewsContainer: { gap: 16, marginBottom: 24 },
  reviewCard: {
    backgroundColor: '#0f172a',
    padding: 16,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#1e293b',
  },
  reviewHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  userInfo: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  userAvatarPlaceholder: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#1e293b', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#334155' },
  avatarText: { color: '#22d3ee', fontWeight: '700', fontSize: 14 },
  userName: { color: '#fff', fontWeight: '600', fontSize: 14 },
  reviewDate: { color: '#64748b', fontSize: 12 },
  ratingBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: 'rgba(34, 211, 238, 0.1)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  ratingText: { color: '#22d3ee', fontWeight: '800', fontSize: 12 },
  reviewComment: { color: '#cbd5e1', fontSize: 14, lineHeight: 20, marginBottom: 12 },
  tagContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  sentimentTag: { backgroundColor: '#020617', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6, borderWidth: 1, borderColor: '#334155' },
  sentimentTagText: { color: '#94a3b8', fontSize: 11, fontWeight: '600' },

  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  writeReviewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(34, 211, 238, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  writeReviewBtnText: { color: '#22d3ee', fontSize: 12, fontWeight: '700' },
  starRatingRow: { flexDirection: 'row', gap: 12, marginBottom: 20, justifyContent: 'center' },
  tagToggleContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 },
  tagToggle: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, borderWidth: 1, borderColor: '#334155', backgroundColor: '#020617' },
  tagToggleActive: { borderColor: '#22d3ee', backgroundColor: 'rgba(34, 211, 238, 0.1)' },
  tagToggleText: { color: '#94a3b8', fontSize: 12, fontWeight: '600' },
  tagToggleTextActive: { color: '#22d3ee' },
  submitReviewBtn: {
    backgroundColor: '#22d3ee',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  submitReviewText: { color: '#020617', fontWeight: '800', fontSize: 16 },

  stickyFooter: {
    backgroundColor: '#020617',
    flexDirection: 'row',
    marginTop: 12,
    marginBottom: 20,
    borderRadius: 14,
    padding: 16,
    paddingBottom: 16,
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(34, 211, 238, 0.2)',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: -4 }, shadowOpacity: 0.3, shadowRadius: 8 },
      android: { elevation: 20 },
      web: { boxShadow: '0px -4px 20px rgba(0,0,0,0.5)' }
    }),
  },
  stickyFooterMobile: {
    flexDirection: 'column',
    gap: 8,
    paddingHorizontal: 12,
  },
  stickyFooterBtnMobile: {
    width: '100%',
    flex: undefined,
  },
  footerSecondaryBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(34, 197, 94, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(34, 197, 94, 0.3)',
    borderRadius: 16,
    height: 50,
  },
  footerSecondaryText: { color: '#22c55e', fontWeight: '700' },
  footerPrimaryBtn: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#22d3ee',
    borderRadius: 16,
    height: 50,
  },
  footerPrimaryText: { color: '#020617', fontWeight: '800', fontSize: 16 },

  toolsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  toolsRowMobile: {
    gap: 8,
  },
  toolButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#0f172a',
    paddingVertical: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1e293b',
  },
  toolButtonText: {
    color: '#e2e8f0',
    fontWeight: '600',
    fontSize: 14,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(2, 6, 23, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#0f172a',
    borderRadius: 24,
    padding: 24,
    width: '100%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: '#1e293b',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: { color: '#fff', fontSize: 20, fontWeight: '800' },
  calcResultLabel: { color: '#94a3b8', textAlign: 'center', fontSize: 13 },
  calcResultValue: { color: '#22d3ee', textAlign: 'center', fontSize: 32, fontWeight: '900', marginVertical: 10 },
  callbackSubtitle: { color: '#94a3b8', fontSize: 14, marginBottom: 20, textAlign: 'center' },
  inputGroup: { marginBottom: 16 },
  inputLabel: { color: '#cbd5e1', fontSize: 14, marginBottom: 8, fontWeight: '600' },
  modalInput: {
    backgroundColor: '#020617',
    borderWidth: 1,
    borderColor: '#334155',
    borderRadius: 12,
    padding: 12,
    color: '#fff',
    fontSize: 16,
  },

  fullScreenModal: { flex: 1, backgroundColor: '#000' },
  tourContent: { height: '100%', position: 'relative' },
  hotspot: {
    position: 'absolute',
    top: '50%',
    transform: [{ translateY: -25 }],
  },
  hotspotInner: {
    backgroundColor: 'rgba(34, 211, 238, 0.8)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 2,
    borderColor: '#fff',
  },
  hotspotText: { color: '#fff', fontWeight: '700', fontSize: 12 },
  tourOverlay: { ...StyleSheet.absoluteFillObject, justifyContent: 'center', alignItems: 'center', gap: 16 },
  tourInstruction: { color: '#fff', fontSize: 16, fontWeight: '600', textShadowColor: 'rgba(0,0,0,0.5)', textShadowRadius: 4 },
  closeTourBtn: {
    position: 'absolute',
    top: 50,
    right: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 10,
    borderRadius: 25,
  },

  breakupList: { gap: 12, marginBottom: 20 },
  breakupRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  breakupLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  breakupLabel: { color: '#94a3b8', fontSize: 14, fontWeight: '600' },
  breakupValue: { color: '#fff', fontSize: 14, fontWeight: '700' },
  totalRow: { borderTopWidth: 1, borderTopColor: '#1e293b', marginTop: 12, paddingTop: 12 },
  totalLabel: { color: '#22d3ee', fontSize: 16, fontWeight: '700' },
  totalValue: { color: '#fff', fontSize: 16, fontWeight: '800' },
  disclaimerText: { color: '#94a3b8', fontSize: 12, marginTop: 8, textAlign: 'center' },

  chartContainer: {
    backgroundColor: '#0f172a',
    padding: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#1e293b',
    marginBottom: 24,
  },
  chartPointerLabel: {
    backgroundColor: '#0f172a',
    padding: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#22d3ee',
  },
  chartPointerText: { color: '#fff', fontWeight: 'bold', fontSize: 12 },
  chartInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: '#1e293b',
    paddingTop: 12,
    marginTop: 10,
  },
  chartTrendText: {
    color: '#22d3ee',
    fontSize: 13,
    fontWeight: '600',
  },

  insightsContainer: {
    backgroundColor: '#0f172a',
    padding: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#1e293b',
    marginBottom: 24,
  },
  insightHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 16 },
  insightTitle: { color: '#fff', fontSize: 16, fontWeight: '700', flex: 1 },
  potentialBadge: { backgroundColor: 'rgba(34, 211, 238, 0.1)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  potentialText: { color: '#22d3ee', fontSize: 10, fontWeight: '800', textTransform: 'uppercase' },
  localityCompareBtn: {
    backgroundColor: 'rgba(34, 211, 238, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(34, 211, 238, 0.3)',
  },
  localityCompareBtnText: { color: '#22d3ee', fontSize: 11, fontWeight: '700' },
  localityStatsRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 20, backgroundColor: '#020617', padding: 16, borderRadius: 12 },
  localityStatItem: { flex: 1, alignItems: 'center' },
  localityStatLabel: { color: '#64748b', fontSize: 11, fontWeight: '600', marginBottom: 4 },
  localityStatValue: { color: '#fff', fontSize: 15, fontWeight: '800' },
  localityStatDivider: { width: 1, height: 30, backgroundColor: '#1e293b' },
  advantagesContainer: { marginBottom: 20, gap: 8 },
  advantageItem: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  advantageText: { color: '#cbd5e1', fontSize: 13 },
  appreciationGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16, backgroundColor: '#020617', padding: 12, borderRadius: 12 },
  appreciationItem: { alignItems: 'center', flex: 1 },
  appreciationLabel: { color: '#64748b', fontSize: 11, fontWeight: '600', marginBottom: 4 },
  appreciationValueRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  appreciationValue: { fontSize: 14, fontWeight: '800' },
  insightDescription: { color: '#94a3b8', fontSize: 13, lineHeight: 18 },

  localityComparisonCard: {
    backgroundColor: '#0f172a',
    padding: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#1e293b',
    marginBottom: 24,
  },
  comparisonHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  comparisonSubTitle: { color: '#94a3b8', fontSize: 13, fontWeight: '600' },
  quickComparisonRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#020617', padding: 16, borderRadius: 12 },
  quickCompItem: { flex: 1, alignItems: 'center' },
  quickCompLabel: { color: '#64748b', fontSize: 11, fontWeight: '600', marginBottom: 4 },
  quickCompValueRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  quickCompValue: { color: '#fff', fontSize: 16, fontWeight: '800' },
  quickCompDivider: { width: 1, height: 24, backgroundColor: '#1e293b' },

  comparisonLegend: { flexDirection: 'row', justifyContent: 'center', gap: 20, marginBottom: 24 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendColor: { width: 10, height: 10, borderRadius: 5 },
  legendText: { color: '#94a3b8', fontSize: 12, fontWeight: '600' },
  localityComparisonGrid: { gap: 20, marginBottom: 24 },
  comparisonMetricRow: { gap: 8 },
  comparisonMetricLabel: { color: '#e2e8f0', fontSize: 14, fontWeight: '600' },
  dualBarContainer: { gap: 4 },
  comparisonValues: { flexDirection: 'row', justifyContent: 'space-between' },
  comparisonValueText: { fontSize: 12, fontWeight: '800', color: '#22d3ee' },
  priceComparisonBox: { backgroundColor: '#020617', padding: 16, borderRadius: 16, marginBottom: 20 },
  priceComparisonRow: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center',
    marginTop: 12 
  },
  priceCompValue: { color: '#22d3ee', fontSize: 16, fontWeight: '800' },
  appreciationCompRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10 },
  appreciationCompLabel: { color: '#94a3b8', fontSize: 12 },
  appreciationCompValues: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  appreciationCompValueText: { color: '#22d3ee', fontSize: 13, fontWeight: '700' },
  advantagesComparisonRow: { flexDirection: 'row', gap: 16, marginTop: 12 },
  advantageTextSmall: { color: '#cbd5e1', fontSize: 11 },

  agentCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0f172a',
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#1e293b',
    marginBottom: 24,
  },
  agentImageContainer: { position: 'relative' },
  agentImage: { width: 54, height: 54, borderRadius: 27 },
  verifiedBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: '#0f172a',
    borderRadius: 10,
  },
  agentInfo: { flex: 1, marginLeft: 12 },
  agentNameRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 2 },
  agentName: { color: '#fff', fontWeight: '700', fontSize: 16 },
  verifiedTextBadge: {
    backgroundColor: 'rgba(34, 211, 238, 0.1)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  verifiedText: { color: '#22d3ee', fontSize: 10, fontWeight: '700' },
  agentTitle: { color: '#94a3b8', fontSize: 13, marginBottom: 4 },
  responseTimeRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  responseTimeText: { color: '#64748b', fontSize: 11, fontWeight: '500' },
  contactButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(34, 211, 238, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },

  locationPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0f172a',
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#1e293b',
    gap: 12,
    marginBottom: 32,
  },
  locationPreviewText: {
    flex: 1,
    color: '#e5e7eb',
    fontSize: 14,
    fontWeight: '500',
  },
  viewMapLink: {
    color: '#22d3ee',
    fontSize: 13,
    fontWeight: '700',
  },

  bookButton: {
    backgroundColor: '#22d3ee',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    marginBottom: 40,
    ...Platform.select({
      ios: {
        shadowColor: '#22d3ee',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.4,
        shadowRadius: 12,
      },
      android: {
        elevation: 8,
      },
      web: {
        boxShadow: '0px 8px 12px rgba(34, 211, 238, 0.4)',
      },
    }),
  },
  bookButtonText: {
    color: '#020617',
    fontSize: 16,
    fontWeight: '800',
  },

  similarScroll: { gap: 16, paddingBottom: 20 },
  similarCard: {
    width: 200,
    backgroundColor: '#0f172a',
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#1e293b',
  },
  similarImage: { width: '100%', height: 120 },
  similarInfo: { padding: 12 },
  similarName: {
    color: '#e5e7eb',
    fontSize: 14,
    fontWeight: '700',
  },
  similarPrice: {
    color: '#22d3ee',
    fontSize: 13,
    fontWeight: '800',
  },
  similarMeta: {
    color: '#94a3b8',
    fontSize: 11,
    marginTop: 2,
  },
  similarBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(34, 211, 238, 0.9)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  similarBadgeText: {
    color: '#020617',
    fontSize: 10,
    fontWeight: '800',
  },
  recommendationHint: {
    color: '#94a3b8',
    fontSize: 12,
    marginTop: -8,
    marginBottom: 12,
  },
  noResultsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#0f172a',
    borderWidth: 1,
    borderColor: '#1e293b',
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  noResultsText: {
    flex: 1,
    color: '#cbd5e1',
    fontSize: 13,
    lineHeight: 18,
  },
  snapshotGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 10,
  },
  snapshotItem: {
    width: '48%',
    backgroundColor: '#020617',
    borderWidth: 1,
    borderColor: '#1e293b',
    borderRadius: 12,
    padding: 12,
  },
  snapshotLabel: {
    color: '#94a3b8',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  snapshotValue: {
    color: '#e2e8f0',
    fontSize: 16,
    fontWeight: '800',
  },
  snapshotDelta: {
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 12,
  },
  snapshotDeltaGood: {
    color: '#22c55e',
  },
  snapshotDeltaWarn: {
    color: '#fbbf24',
  },
  signalList: {
    gap: 8,
  },
  signalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 2,
  },
  signalText: {
    flex: 1,
    color: '#cbd5e1',
    fontSize: 13,
    lineHeight: 18,
  },
  timeText: { color: '#fff', fontSize: 12, fontWeight: '600' },

  aiInsightPanel: {
    backgroundColor: '#071025',
    borderWidth: 1,
    borderColor: '#16324a',
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
  },
  aiInsightHeading: { color: '#22d3ee', fontWeight: '800', fontSize: 14, marginBottom: 8 },
  aiInsightText: { color: '#cbd5e1', fontSize: 13, lineHeight: 20 },

  demandContainer: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#062033' },
  demandRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  demandEmoji: { fontSize: 16 },
  demandText: { color: '#cbd5e1', fontSize: 13 },
  demandHighlight: { color: '#fbbf24', fontWeight: '800' },

  roiContainer: {
    backgroundColor: '#0f172a',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1e293b',
    marginBottom: 24,
  },
  roiInputRow: { marginBottom: 12 },
  roiInput: {
    backgroundColor: '#020617',
    borderWidth: 1,
    borderColor: '#334155',
    borderRadius: 12,
    padding: 10,
    color: '#fff',
    fontSize: 15,
  },
  roiCard: {
    backgroundColor: '#071025',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#16324a',
  },
  roiMetricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#062033',
  },
  roiMetricIcon: { fontSize: 20 },
  roiLabel: { color: '#94a3b8', fontSize: 12, fontWeight: '700' },
  roiValue: { color: '#22d3ee', fontSize: 20, fontWeight: '900' },
  roiBadge: { backgroundColor: '#22d3ee', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, marginLeft: 8 },
  roiBadgeText: { color: '#020617', fontSize: 12, fontWeight: '800' },
  sectionCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(30, 41, 59, 0.8)',
    borderLeftWidth: 6,
  },
  sectionCardMobile: {
    padding: 18,
    borderRadius: 18,
  },
  sectionCardSmall: {
    padding: 14,
    borderRadius: 16,
  },
  sectionCardHover: {
    backgroundColor: 'rgba(30, 41, 59, 0.6)',
    borderColor: 'rgba(34, 211, 238, 0.4)',
    ...Platform.select({
      web: {
        transform: [{ scale: 1.01 }],
        transition: 'all 0.3s ease',
      }
    })
  },

  compareSelectItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#020617',
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
    gap: 12,
  },
  compareSelectImg: { width: 50, height: 50, borderRadius: 8 },
  compareSelectName: { color: '#fff', fontWeight: '700', fontSize: 14 },
  compareSelectPrice: { color: '#22d3ee', fontSize: 12, fontWeight: '600' },
  compareTable: {
    backgroundColor: '#020617',
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#1e293b',
    marginBottom: 20,
  },
  compareRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#1e293b' },
  compareCellHeader: { flex: 1, padding: 12, color: '#94a3b8', fontSize: 11, fontWeight: '800', textTransform: 'uppercase', backgroundColor: '#1e293b' },
  compareLabelCell: { flex: 1, padding: 12, color: '#cbd5e1', fontSize: 13, fontWeight: '600' },
  compareValueCell: { flex: 1, padding: 12, color: '#fff', fontSize: 13, fontWeight: '700' },
  resetCompareBtn: {
    padding: 12,
    alignItems: 'center',
    backgroundColor: 'rgba(34, 211, 238, 0.1)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(34, 211, 238, 0.3)',
  },
  resetCompareText: { color: '#22d3ee', fontWeight: '700', fontSize: 14 },

  /* Trust Builder Styles */
  trustBuilderContainer: { marginBottom: 24, gap: 12 },
  trustSummaryCard: {
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.3)',
    marginBottom: 8,
  },
  trustSummaryGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 12,
  },
  trustSummaryText: { color: '#e2e8f0', fontSize: 13, flex: 1, lineHeight: 18 },
  trustCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0f172a',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1e293b',
  },
  trustRatingRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 4 },
  trustScore: { color: '#fff', fontSize: 12, fontWeight: '700' },
  trustReviewCount: { color: '#64748b', fontSize: 11 },
  trustBadge: { backgroundColor: 'rgba(34, 211, 238, 0.1)', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  trustBadgeText: { color: '#22d3ee', fontSize: 9, fontWeight: '800' },
  topSchoolBadge: {
    backgroundColor: 'rgba(251, 191, 36, 0.1)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.3)',
  },
  topSchoolBadgeText: {
    color: '#fbbf24',
    fontSize: 10,
    fontWeight: '700',
  },
  emergencyBadge: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  emergencyBadgeText: {
    color: '#ef4444',
    fontSize: 10,
    fontWeight: '700',
  },
  filterSection: { marginBottom: 20 },
  saveSearchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(34, 211, 238, 0.1)',
    borderWidth: 1,
    borderColor: '#22d3ee',
    paddingVertical: 12,
    borderRadius: 12,
    marginBottom: 12,
  },
  saveSearchBtnActive: { backgroundColor: '#22d3ee' },
  saveSearchText: { color: '#22d3ee', fontWeight: '700', fontSize: 14 },
  saveSearchTextActive: { color: '#020617' },
  recentSearchChip: {
    backgroundColor: '#1e293b',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#334155',
  },
  recentSearchText: {
    color: '#e2e8f0',
    fontSize: 12,
    fontWeight: '600',
  },
  clearAllText: { color: '#22d3ee', fontSize: 14, fontWeight: '700' },
  priceDropToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
    backgroundColor: 'rgba(148, 163, 184, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  priceDropToggleActive: { backgroundColor: '#fbbf24', borderColor: '#fbbf24' },
  priceDropText: { color: '#94a3b8', fontSize: 11, fontWeight: '700' },
  priceDropTextActive: { color: '#020617' },
  featuredBadge: {
    position: 'absolute',
    top: 100,
    left: 20,
    backgroundColor: '#fbbf24',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    zIndex: 10,
  },
  featuredBadgeText: { color: '#020617', fontSize: 10, fontWeight: '900' },
  agentToolsRow: { flexDirection: 'row', gap: 12, marginTop: 20, borderTopWidth: 1, borderTopColor: '#1e293b', paddingTop: 20 },
  agentToolBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(34, 211, 238, 0.05)',
    borderWidth: 1,
    borderColor: '#22d3ee',
    paddingVertical: 10,
    borderRadius: 12,
  },
  agentToolBtnText: { color: '#22d3ee', fontWeight: '700', fontSize: 13 },
  leadCard: { backgroundColor: '#020617', padding: 16, borderRadius: 16, marginBottom: 12, borderWidth: 1, borderColor: '#1e293b' },
  leadName: { color: '#fff', fontSize: 16, fontWeight: '700' },
  leadStatusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  leadStatusText: { color: '#fff', fontSize: 10, fontWeight: '800' },
  leadMetaText: { color: '#94a3b8', fontSize: 11 },
  leadNotes: { color: '#cbd5e1', fontSize: 13, fontStyle: 'italic' },
  boostPlanCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#020617',
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#334155',
  },
  boostPlanLabel: { color: '#94a3b8', fontSize: 14, fontWeight: '600' },
  boostPlanPrice: { color: '#fff', fontSize: 18, fontWeight: '800' },
  bestDealBadge: { backgroundColor: 'rgba(34, 197, 94, 0.15)', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  bestDealText: { color: '#22c55e', fontSize: 9, fontWeight: '800' },
  bankTable: { backgroundColor: '#020617', borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: '#1e293b' },
  bankTableHeader: { flexDirection: 'row', backgroundColor: '#1e293b', padding: 12 },
  bankHeaderCell: { flex: 1, color: '#94a3b8', fontSize: 11, fontWeight: '800', textTransform: 'uppercase' },
  bankRow: { flexDirection: 'row', padding: 12, borderBottomWidth: 1, borderBottomColor: '#1e293b', alignItems: 'center' },
  bankName: { color: '#fff', fontWeight: '700', fontSize: 14 },
  bankRate: { flex: 1, color: '#22d3ee', fontWeight: '800', fontSize: 14 },
  bankEMI: { flex: 1, color: '#fff', fontWeight: '800', fontSize: 14, textAlign: 'right' },
  bankOffersContainer: { gap: 10 },
  bankOfferItem: {
    flexDirection: 'row',
    gap: 12,
    backgroundColor: 'rgba(251, 191, 36, 0.05)',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.2)',
  },
  bankOfferTitle: { color: '#fbbf24', fontSize: 12, fontWeight: '800', textTransform: 'uppercase' },
  bankOfferText: { color: '#cbd5e1', fontSize: 13, marginTop: 2 },
  trustScoreContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
  trustScoreLabel: { color: '#94a3b8', fontSize: 12, fontWeight: '600' },
  trustScoreValue: { fontSize: 12, fontWeight: '800' },
  trustScoreHero: { alignItems: 'center', marginVertical: 20 },
  trustScoreHeroValue: { fontSize: 48, fontWeight: '900' },
  trustScoreHeroLabel: { color: '#94a3b8', fontSize: 14, fontWeight: '600', marginTop: 4 },
  trustBreakdownList: { gap: 16, marginBottom: 24 },
  trustBreakdownItem: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  trustItemIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#020617', justifyContent: 'center', alignItems: 'center' },
  trustItemLabel: { color: '#e2e8f0', fontSize: 13, fontWeight: '600', marginBottom: 4 },
  trustItemBarBg: { height: 4, backgroundColor: '#020617', borderRadius: 2, overflow: 'hidden' },
  trustItemBarFill: { height: '100%', borderRadius: 2 },
  trustItemScore: { color: '#fff', fontSize: 12, fontWeight: '800', width: 45, textAlign: 'right' },
  fairnessBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 2 },
  fairnessText: { fontSize: 11, fontWeight: '700' },
  aiInsightHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  aiScoreRow: { flexDirection: 'row', alignItems: 'baseline', gap: 2, marginTop: 4 },
  aiScoreValue: { color: '#22d3ee', fontSize: 24, fontWeight: '900' },
  aiScoreMax: { color: '#475569', fontSize: 14, fontWeight: '700' },
  bestForBadge: { backgroundColor: 'rgba(34, 211, 238, 0.1)', padding: 8, borderRadius: 12, alignItems: 'flex-end' },
  bestForLabel: { color: '#94a3b8', fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  bestForValue: { color: '#e2e8f0', fontSize: 12, fontWeight: '800', marginTop: 2 },
  chatBubble: { padding: 12, borderRadius: 16, maxWidth: '85%' },
  aiBubble: { backgroundColor: '#1e293b', alignSelf: 'flex-start', borderBottomLeftRadius: 4 },
  userBubble: { backgroundColor: '#22d3ee', alignSelf: 'flex-end', borderBottomRightRadius: 4 },
  chatText: { fontSize: 14, lineHeight: 20 },
  aiChatText: { color: '#e2e8f0' },
  userChatText: { color: '#020617', fontWeight: '500' },
  chatInputContainer: { flexDirection: 'row', gap: 10, paddingTop: 15, borderTopWidth: 1, borderTopColor: '#1e293b' },
  chatInput: { flex: 1, backgroundColor: '#020617', borderRadius: 12, paddingHorizontal: 15, paddingVertical: 10, color: '#fff', fontSize: 14, borderWidth: 1, borderColor: '#334155' },
  chatSendBtn: { backgroundColor: '#22d3ee', width: 44, height: 44, borderRadius: 22, justifyContent: 'center', alignItems: 'center' },
  voiceSearchBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(34, 211, 238, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(34, 211, 238, 0.3)',
  },
  voiceSearchBtnActive: { backgroundColor: '#ef4444', borderColor: '#ef4444' },
  docItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0f172a',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    gap: 12,
    borderWidth: 1,
    borderColor: '#1e293b',
  },
  docName: {
    flex: 1,
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  docStatus: {
    color: '#22c55e',
    fontSize: 12,
    fontWeight: '700',
  },
  constructionContainer: {
    backgroundColor: '#0f172a',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#1e293b',
    marginBottom: 20,
  },
  constructionPhotoCard: {
    marginRight: 12,
    width: 140,
  },
  constructionPhoto: {
    width: '100%',
    height: 90,
    borderRadius: 10,
  },
  constructionMonth: {
    color: '#94a3b8',
    fontSize: 12,
    marginTop: 6,
    textAlign: 'center',
  },
  progressStatusCard: {
    backgroundColor: '#020617',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#1e293b',
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  progressStatusTitle: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: '700',
    flex: 1,
    marginRight: 8,
  },
  onTrackBadge: {
    backgroundColor: 'rgba(34, 197, 94, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(34, 197, 94, 0.3)',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  onTrackText: {
    color: '#22c55e',
    fontSize: 10,
    fontWeight: '800',
  },
  progressDetail: {
    color: '#94a3b8',
    fontSize: 12,
    lineHeight: 18,
  },
  visitTrackerCard: {
    backgroundColor: '#0f172a',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#1e293b',
    marginBottom: 20,
  },
  visitTrackerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  visitTrackerTitle: {
    color: '#e2e8f0',
    fontSize: 16,
    fontWeight: '700',
  },
  completeVisitBtn: {
    backgroundColor: '#22d3ee',
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
  completeVisitBtnText: {
    color: '#020617',
    fontWeight: '800',
  },
  visitPointsText: {
    color: '#22c55e',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 10,
  },
  feedbackBtn: {
    backgroundColor: 'rgba(34, 211, 238, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(34, 211, 238, 0.35)',
    borderRadius: 10,
    paddingVertical: 9,
    alignItems: 'center',
  },
  feedbackBtnText: {
    color: '#22d3ee',
    fontWeight: '700',
  },
});

